---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-summary.html 
keywords: NetApp Solutions, hybrid, Multicloud, enterprise hybrid cloud, hyperscalers, vmware 
summary:  
---
= 總結與結論： NetApp為何選擇 VMware 作為混合多雲平台
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp Cloud Volumes 與主要超大規模企業的 VMware 解決方案為希望利用混合雲的組織提供了巨大的潛力。本節的其餘部分提供了用例，表明整合NetApp Cloud Volumes 可以實現真正的混合多雲功能。



== 用例 #1：優化存儲

當使用 RVtools 輸出執行大小調整練習時，馬力（vCPU/vMem）比例與儲存平行是顯而易見的。很多時候，組織會發現他們所處的境地是，所需的儲存空間使叢集的規模遠遠超出了馬力所需的範圍。

透過整合NetApp Cloud Volumes，組織可以透過簡單的遷移方法實現基於 vSphere 的雲端解決方案，無需重新平台化、無需 IP 變更、無需架構變更。此外，透過此最佳化，您可以擴充儲存空間，同時將主機數量保持在 vSphere 所需的最少量，但不會改變儲存層次結構、安全性或可用的檔案。這使您可以優化部署並將總體 TCO 降低 35–45%。透過這種集成，您還可以在幾秒鐘內將儲存空間從熱儲存擴展到生產級效能。



== 用例2：雲端遷移

由於多種原因，組織面臨著將應用程式從本地資料中心遷移到公有雲的壓力：租約即將到期；財務指令要求從資本支出 (capex) 轉向營運支出 (opex)；或者僅僅是自上而下的命令要求將所有內容遷移到雲端。

當速度至關重要時，只有簡化的遷移方法是可行的，因為重新平台化和重構應用程式以適應雲端的特定 IaaS 平台既緩慢又昂貴，通常需要數月時間。透過將NetApp Cloud Volumes 與用於客戶端連接儲存的頻寬高效的SnapMirror複製（包括與應用程式一致的 Snapshot 副本和 HCX 結合的 RDM、特定於雲端的遷移（例如 Azure Migrate）或用於複製虛擬機器的第三方產品）相結合，這種轉變比依賴過濾機制更容易。



== 用例3：資料中心擴展

當資料中心因季節性需求高峰或僅僅是穩定的有機成長而達到容量限制時，遷移到雲端託管的 VMware 以及NetApp Cloud Volumes 是一個簡單的解決方案。利用NetApp Cloud Volumes，可以透過提供跨可用區域的高可用性和動態擴充功能，非常輕鬆地建立、複製和擴充儲存。利用NetApp Cloud Volumes 有助於克服對延伸叢集的需求，從而最大限度地減少主機叢集容量。



== 用例 #4：災難復原至雲端

在傳統方法中，如果發生災難，複製到雲端的虛擬機器需要轉換到雲端自己的虛擬機器管理程式平台才能恢復 - 這不是危機期間要處理的任務。

透過使用NetApp Cloud Volumes 進行來賓連接存儲，使用來自本地的SnapCenter和SnapMirror複製以及公共雲虛擬化解決方案，可以設計出一種更好的災難恢復方法，允許在完全一致的 VMware SDDC 基礎架構上恢復虛擬機副本以及特定於雲端的恢復工具（例如 Azure Site Recovery）或等效的第三方工具（如 Veeam）。這種方法還使您能夠快速執行災難復原演習和勒索軟體復原。透過按需添加主機，您還可以擴展到全面生產以進行測試或在災難期間進行擴展。



== 用例 #5：應用程式現代化

應用程式進入公有雲後，組織將希望利用數百種強大的雲端服務來實現其現代化和擴展。透過使用NetApp Cloud Volumes，現代化是一個簡單的過程，因為應用程式資料不會被鎖定在 vSAN 中，並且允許在包括 Kubernetes 在內的廣泛用例中實現資料移動。



== 結論

無論您的目標是全雲還是混合雲， NetApp Cloud Volumes 都提供了出色的選項來部署和管理應用程式工作負載以及檔案服務和區塊協議，同時透過使資料需求無縫連接到應用程式層來降低 TCO。

無論使用情況如何，選擇您最喜歡的雲端/超大規模器以及NetApp Cloud Volumes，以快速實現雲端優勢、一致的基礎架構和跨本地和多個雲端的操作、工作負載的雙向可移植性以及企業級容量和效能。

它與用於連接儲存的熟悉的過程和程序相同。請記住，新名稱只是改變了資料的位置；工具和流程都保持不變， NetApp Cloud Volumes 有助於優化整體部署。
