---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-storage.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= 面向公有雲提供者的NetApp儲存選項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
探索NetApp在三大超大規模資料中心中作為儲存的選項。

[role="tabbed-block"]
====
.AWS/VMC
--
AWS 支援以下配置的NetApp儲存：

* FSx ONTAP作為來賓連接存儲
* Cloud Volumes ONTAP (CVO) 作為來賓連接存儲
* FSx ONTAP作為補充 NFS 資料存儲


查看詳細信息link:../vmware/vmw-aws-vmc-guest-storage.html["VMC 的用戶機連線儲存選項"]。查看詳細信息link:../vmware/vmw-aws-vmc-nfs-ds-config.html["VMC 的補充 NFS 資料儲存選項"]。

--
.Azure/AVS
--
Azure 支援以下配置的NetApp儲存體：

* Azure NetApp Files(ANF) 作為來賓連接儲存
* Cloud Volumes ONTAP (CVO) 作為來賓連接存儲
* Azure NetApp Files(ANF) 作為補充 NFS 資料存儲


查看詳細信息link:../vmware/vmw-azure-avs-guest-storage.html["AVS 的來賓連線儲存選項"]。查看詳細信息link:../vmware/vmw-azure-avs-nfs-ds-config.html["AVS 的補充 NFS 資料儲存選項"]。

--
.良好操作規範/良好行為規範
--
Google Cloud 支援以下配置的NetApp儲存：

* Cloud Volumes ONTAP (CVO) 作為來賓連接存儲
* Google Cloud NetApp Volumes （NetApp Volumes）作為來賓連接存儲
* Google Cloud NetApp Volumes （NetApp Volumes）作為補充 NFS 資料存儲


查看詳細信息link:../vmware/vmw-gcp-gcve-guest-storage.html["GCVE 的來賓連接儲存選項"]。查看詳細信息link:../vmware/vmw-gcp-gcve-nfs-ds-overview.html["GCVE 的補充 NFS 資料儲存選項"]。

閱讀更多link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Google Cloud NetApp Volumes資料儲存區支援 Google Cloud VMware Engine（NetApp部落格）"^]或者link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["如何將Google Cloud NetApp Volumes用作 Google Cloud VMware Engine 的資料儲存區（Google 部落格）"^]

--
====