---
sidebar: sidebar 
permalink: vmware/vmw-hybrid-use-cases.html 
keywords: NetApp Solutions, ehc, enterprise hybrid cloud, use case, hyperscalers, vmware 
summary:  
---
= NetApp與 VMware 混合多雲的用例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
概述在規劃混合雲或雲端優先部署時對 IT 組織重要的用例。



== 熱門用例

用例包括：

* 災難恢復，
* 在資料中心維護期間託管工作負載，* 快速爆發，需要超出本地資料中心配置的額外資源，
* VMware 站點擴展，
* 快速遷移到雲端，
* 開發/測試，以及
* 利用雲端補充技術實現應用程式的現代化。


在本文檔中，將使用 VMware 用例詳細說明雲端工作負載參考。這些用例是：

* 保護（包括災難復原和備份/還原）
* 遷移
* 延長




=== IT 之旅

大多數組織都處於轉型和現代化的旅程中。作為此過程的一部分，該公司正在嘗試利用其現有的 VMware 投資，同時利用雲端優勢並探索使遷移過程盡可能無縫的方法。由於資料已經在雲端，這種方法將使他們的現代化工作變得非常容易。

對於這種情況最簡單的答案是每個超大規模企業都提供 VMware 產品。與NetApp Cloud Volumes 一樣，VMware 提供了一種將本機 VMware 環境移動或擴展到任何雲端的方法，使您能夠保留現有的本機資產、技能和工具，同時在雲端中本地運行工作負載。這降低了風險，因為不會出現服務中斷或需要更改 IP，並使 IT 團隊能夠使用現有技能和工具以在本地的方式進行操作。這可以加速雲端遷移並更順利地過渡到混合多雲架構。



=== 了解補充 NFS 儲存選項的重要性

雖然任何雲端中的 VMware 都為每個客戶提供了獨特的混合功能，但有限的補充 NFS 儲存選項限制了其對於儲存工作負載繁重的組織的實用性。由於儲存直接與主機綁定，因此擴展儲存的唯一方法是添加更多主機 - 而這會使儲存密集型工作負載的成本增加 35-40％ 或更多。這些工作負載只需要額外的儲存空間，而不是額外的馬力。但這意味著需要支付額外的主機費用。

讓我們考慮一下這種情況：

一個客戶只需要五台主機用於 CPU 和內存，但有大量的儲存需求，需要 12 台主機來滿足儲存需求。當他們只需要增加儲存空間時，這個要求最終會真正打破財務平衡，因為他們必須購買額外的馬力。

當您規劃雲端採用和遷移時，評估最佳方法並採取最簡單的途徑來減少總投資始終非常重要。對於任何應用程式遷移來說，最常見且最簡單的方法是重新託管（也稱為提升和轉移），其中不需要虛擬機器（VM）或資料轉換。將NetApp Cloud Volumes 與 VMware 軟體定義資料中心 (SDDC) 結合使用，在補充 vSAN 的同時，提供了簡單的提升和轉移選項。
